[build]
  publish = "/"
  command = "echo 'No build required - static site'"

[dev]
  command = "npx serve"
  port = 8888
  targetPort = 8888
  framework = "#static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200